// <auto-generated />
using System;
using FabricaPastas.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabricaPastas.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251109214144_registro")]
    partial class registro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Categoria_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Producto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IngredientesBase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcesoElaboracion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tamanio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo_Pasta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Tipo_Pasta", "Forma", "Tamanio", "IngredientesBase", "ProcesoElaboracion" }, "Tipo_Pasta_Forma_Tamanio_IngredientesBase_ProcesoElaboracion");

                    b.ToTable("Categoria_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Lista_Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Detalle_Lista_Id")
                        .HasColumnType("int");

                    b.Property<int>("Lista_Precio_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio_Personalizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Precio_Personalizado" }, "Precio_Personalizado");

                    b.ToTable("Detalle_Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Detalle_Pedido_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Cantidad", "Precio_Unitario" }, "Cantidad_Precio_Unitario");

                    b.ToTable("Detalle_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Estado_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Estado_Pedido_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Descripcion" }, "Descripcion");

                    b.ToTable("Estado_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Forma_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Forma_Pago_Id")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Metodo" }, "Metodo");

                    b.ToTable("Forma_Pago");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Lista_Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo_Lista_Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha_Desde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Hasta")
                        .HasColumnType("date");

                    b.Property<int>("Lista_Precio_Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Fecha_Desde", "Fecha_Hasta" }, "Fecha_Desde_Fecha_Hasta");

                    b.ToTable("Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Metodo_Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Metodo_Entrega_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Descripcion" }, "Descripcion");

                    b.ToTable("Metodo_entrega");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado_Pedido_Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha_Entrega")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Pedido")
                        .HasColumnType("date");

                    b.Property<int>("Forma_Pago_Id")
                        .HasColumnType("int");

                    b.Property<int>("Metodo_Entrega_Id")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones_Catering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Fecha_Pedido", "Total" }, "Fecha_Pedido_Total");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Producto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imagen_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre", "Descripcion", "PrecioBase", "Imagen_Url", "Stock" }, "Nombre_Descripcion_PrecioBase_Imagen_Url_Stock");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("Fecha_Fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Titulo", "Descripcion", "Fecha_Inicio", "Fecha_Fin", "Activa" }, "Titulo_Descripcion_Fecha_Inicio_Fecha_Fin_Activa");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre_Producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio_Promocional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Promocion_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Fecha_Fin_Promo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio_Promo")
                        .HasColumnType("date");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Usuario_Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Promocion_Usuario");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Tipo_Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<int>("Tipo_Cliente_Id")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo_Cliente_Id");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Cliente");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cuit_Cuil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo_Cliete_Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
