// <auto-generated />
using System;
using FabricaPastas.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabricaPastas.BD.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Categoria_Producto", b =>
                {
                    b.Property<int>("Categoria_Producto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Categoria_Producto_Id"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Categoria_Producto_Id");

                    b.HasIndex(new[] { "Categoria_Producto_Id" }, "Categoria_Producto_Id_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre_Categoria" }, "Nombre_Categoria");

                    b.ToTable("Categoria_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Lista_Precio", b =>
                {
                    b.Property<int>("Detalle_Lista_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Detalle_Lista_Id"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Lista_Precio_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio_Personalizado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Detalle_Lista_Id");

                    b.HasIndex(new[] { "Detalle_Lista_Id" }, "Detalle_Lista_Id_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Precio_Personalizado" }, "Precio_Personalizado");

                    b.ToTable("Detalle_Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Detalle_Pedido", b =>
                {
                    b.Property<int>("Detalle_Pedido_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Detalle_Pedido_Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Detalle_Pedido_Id");

                    b.HasIndex(new[] { "Cantidad", "Precio_Unitario" }, "Cantidad_Precio_Unitario");

                    b.HasIndex(new[] { "Detalle_Pedido_Id" }, "Detalle_Pedido_Id_UQ")
                        .IsUnique();

                    b.ToTable("Detalle_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Estado_Pedido", b =>
                {
                    b.Property<int>("Estado_Pedido_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Estado_Pedido_Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Estado_Pedido_Id");

                    b.HasIndex(new[] { "Descripcion" }, "Descripcion");

                    b.HasIndex(new[] { "Estado_Pedido_Id" }, "Estado_Pedido_Id_UQ")
                        .IsUnique();

                    b.ToTable("Estado_Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Forma_Pago", b =>
                {
                    b.Property<int>("Forma_Pago_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Forma_Pago_Id"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Forma_Pago_Id");

                    b.HasIndex(new[] { "Forma_Pago_Id" }, "Forma_Pago_Id_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Metodo" }, "Metodo");

                    b.ToTable("Forma_Pago");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Lista_Precio", b =>
                {
                    b.Property<int>("Lista_Precio_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lista_Precio_Id"));

                    b.Property<DateOnly>("Fecha_Desde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Hasta")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Lista_Precio_Id");

                    b.HasIndex(new[] { "Fecha_Desde", "Fecha_Hasta" }, "Fecha_Desde_Fecha_Hasta");

                    b.HasIndex(new[] { "Lista_Precio_Id" }, "Lista_Precio_Id_UQ")
                        .IsUnique();

                    b.ToTable("Lista_Precio");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Metodo_Entrega", b =>
                {
                    b.Property<int>("Metodo_Entrega_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Metodo_Entrega_Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Metodo_Entrega_Id");

                    b.HasIndex(new[] { "Descripcion" }, "Descripcion");

                    b.HasIndex(new[] { "Metodo_Entrega_Id" }, "Metodo_Entrega_Id_UQ")
                        .IsUnique();

                    b.ToTable("Metodo_entrega");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Pedido", b =>
                {
                    b.Property<int>("Pedido_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pedido_Id"));

                    b.Property<int>("Estado_Pedido_Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha_Pedido")
                        .HasColumnType("date");

                    b.Property<int>("Forma_Pago_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Metodo_Entrega_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Pedido_Id");

                    b.HasIndex(new[] { "Fecha_Pedido", "Total" }, "Fecha_Pedido_Total");

                    b.HasIndex(new[] { "Pedido_Id" }, "Pedido_Id")
                        .IsUnique();

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Producto", b =>
                {
                    b.Property<int>("Producto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Producto_Id"));

                    b.Property<int>("Categoria_Producto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Imagen_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Producto_Id");

                    b.HasIndex(new[] { "Nombre", "Descripcion", "PrecioBase", "Imagen_Url", "Stock" }, "Nombre_Descripcion_PrecioBase_Imagen_Url_Stock");

                    b.HasIndex(new[] { "Producto_Id" }, "Producto_Id_UQ")
                        .IsUnique();

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion", b =>
                {
                    b.Property<int>("Promocion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promocion_Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("Fecha_Fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Promocion_Id");

                    b.HasIndex(new[] { "Promocion_Id" }, "Promocion_Id_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Titulo", "Descripcion", "Fecha_Inicio", "Fecha_Fin", "Activa" }, "Titulo_Descripcion_Fecha_Inicio_Fecha_Fin_Activa");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Producto", b =>
                {
                    b.Property<int>("Promocion_Producto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promocion_Producto_Id"));

                    b.Property<decimal>("Descuento_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Promocional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.HasKey("Promocion_Producto_Id");

                    b.HasIndex(new[] { "Descuento_Porcentaje", "Precio_Promocional" }, "Descuento_Porcentaje_Precio_Promocional");

                    b.HasIndex(new[] { "Promocion_Producto_Id" }, "Promocion_Producto_Id_UQ")
                        .IsUnique();

                    b.ToTable("Promocion_Producto");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Promocion_Usuario", b =>
                {
                    b.Property<int>("Promocion_Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promocion_Usuario_Id"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Promocion_Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Promocion_Usuario_Id");

                    b.ToTable("Promocion_Usuario");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Rol", b =>
                {
                    b.Property<int>("Rol_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rol_Id"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Rol_Id");

                    b.HasIndex(new[] { "Nombre_rol" }, "Nombre_rol");

                    b.HasIndex(new[] { "Rol_Id" }, "Rol_Id_UQ")
                        .IsUnique();

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Tipo_Cliente", b =>
                {
                    b.Property<int>("Tipo_Cliente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tipo_Cliente_Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Tipo_Cliente_Id");

                    b.HasIndex(new[] { "Descripcion" }, "Descripcion");

                    b.HasIndex(new[] { "Tipo_Cliente_Id" }, "Tipo_Cliente_Id_UQ")
                        .IsUnique();

                    b.ToTable("Tipo_Cliente");
                });

            modelBuilder.Entity("FabricaPastas.BD.Data.Entity.Usuario", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usuario_Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cuit_Cuil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("Fecha_Registro")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo_Cliete_Id")
                        .HasColumnType("int");

                    b.HasKey("Usuario_Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
